export const DISCOVER_QUERIES: string[] = [
  'general contractor',
  'construction company',
  'electrician contractor',
  'plumber plumbing',
  'HVAC contractor',
  'landscaping company',
  'concrete contractor',
  'fencing company',
  'welding fabrication',
  'demolition contractor',
  'excavation grading',
  'paving company',
  'masonry contractor',
  'manufacturing company',
  'machine shop',
  'sheet metal fabrication',
  'metal works industrial',
  'steel fabrication',
  'CNC machining',
];
