// Discover query categories for Places (New) API searches.
// Construction/trades focused — swap these for other industries.
export const DISCOVER_QUERIES: string[] = [
  "general contracting",
  "commercial roofing contractor",
  "plumbing contractor",
  "electrical contractor",
  "HVAC contractor",
  "concrete contractor",
  "framing contractor",
  "insulation contractor",
  "drywall contractor",
  "flooring contractor",
  "painting contractor",
  "landscaping contractor",
  "pool contractor",
  "masonry contractor",
  "window installation",
  "door installation",
  "solar panel installer",
  "home builder",
  "construction company",
  "onshore drilling contractor",
  "offshore drilling company",
  "metal fabricator",
  "welding",
  "manufacturers",
  "structural contractor",
  "paving contractor",
  "demolition contractor",
  "environmental contractor",
  "property restoration",
  "carpenter",
  "stucco contractor",
  "crane operator",
  "service repair",
  "bridge structural ironworkers",
  "millwrights",
  "sheet metal workers",
  "machinists",
  "computer numerical control operators",
  "scaffolding contractor",
  "civil construction company",
  "asphalt contractor",
  "site development contractor",
  "telecommunications contractor",
  "utilities contractor",
];
