export interface DiscoverCategory {
  id: string;
  label: string;
  nearbyPrimaryType: string | null;
  textQuery: string;
  textIncludedType: string | null;
  minNearbyResultsBeforeFallback: number;
}

export const DISCOVER_CATEGORIES: readonly DiscoverCategory[] = [
  // === Core trades ===
  {
    id: "general-contractor",
    label: "General Contractor",
    // `general_contractor` is response-only (not valid for Nearby/Text type filters).
    nearbyPrimaryType: null,
    textQuery: "general contractor",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 3,
  },
  {
    id: "roofing",
    label: "Roofing",
    nearbyPrimaryType: "roofing_contractor",
    textQuery: "roofing contractor",
    textIncludedType: "roofing_contractor",
    minNearbyResultsBeforeFallback: 3,
  },
  {
    id: "plumbing",
    label: "Plumbing",
    nearbyPrimaryType: "plumber",
    textQuery: "plumbing contractor",
    textIncludedType: "plumber",
    minNearbyResultsBeforeFallback: 3,
  },
  {
    id: "electrical",
    label: "Electrical",
    nearbyPrimaryType: "electrician",
    textQuery: "electrical contractor",
    textIncludedType: "electrician",
    minNearbyResultsBeforeFallback: 3,
  },
  {
    id: "painting",
    label: "Painting",
    nearbyPrimaryType: "painter",
    textQuery: "painting contractor",
    textIncludedType: "painter",
    minNearbyResultsBeforeFallback: 2,
  },
  {
    id: "hvac",
    label: "HVAC",
    nearbyPrimaryType: null,
    textQuery: "HVAC contractor",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },
  {
    id: "concrete",
    label: "Concrete",
    nearbyPrimaryType: null,
    textQuery: "concrete contractor",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },
  {
    id: "framing",
    label: "Framing",
    nearbyPrimaryType: null,
    textQuery: "framing contractor",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },
  {
    id: "drywall",
    label: "Drywall",
    nearbyPrimaryType: null,
    textQuery: "drywall contractor",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },
  {
    id: "flooring",
    label: "Flooring",
    nearbyPrimaryType: null,
    textQuery: "flooring contractor",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },
  {
    id: "insulation",
    label: "Insulation",
    nearbyPrimaryType: null,
    textQuery: "insulation contractor",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },
  {
    id: "masonry",
    label: "Masonry",
    nearbyPrimaryType: null,
    textQuery: "masonry contractor",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },
  {
    id: "window-installation",
    label: "Window Installation",
    nearbyPrimaryType: null,
    textQuery: "window installation",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },
  {
    id: "solar",
    label: "Solar",
    nearbyPrimaryType: null,
    textQuery: "solar panel installer",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },

  // === Builder / general ===
  {
    id: "structural-contractor",
    label: "Structural",
    nearbyPrimaryType: null,
    textQuery: "structural contractor",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },
  {
    id: "industrial-contractor",
    label: "Industrial",
    nearbyPrimaryType: null,
    textQuery: "industrial contractor",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },

  // === Site & civil ===
  {
    id: "civil",
    label: "Civil",
    nearbyPrimaryType: null,
    textQuery: "civil construction company",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },
  {
    id: "excavation",
    label: "Excavation",
    nearbyPrimaryType: null,
    textQuery: "excavation contractor",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },
  {
    id: "paving",
    label: "Paving",
    nearbyPrimaryType: null,
    textQuery: "paving contractor",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },
  {
    id: "demolition",
    label: "Demolition",
    nearbyPrimaryType: null,
    textQuery: "demolition contractor",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },
  {
    id: "underground-utilities",
    label: "Underground Utilities",
    nearbyPrimaryType: null,
    textQuery: "underground utilities contractor",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },

  // === Concrete chain ===
  {
    id: "rebar",
    label: "Rebar",
    nearbyPrimaryType: null,
    textQuery: "rebar contractor",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },
  {
    id: "ready-mix-concrete",
    label: "Ready-Mix Concrete",
    nearbyPrimaryType: null,
    textQuery: "ready mix concrete supplier",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },
  {
    id: "precast-concrete",
    label: "Precast Concrete",
    nearbyPrimaryType: null,
    textQuery: "precast concrete manufacturer",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },

  // === Building specialty ===
  {
    id: "mechanical",
    label: "Mechanical",
    nearbyPrimaryType: null,
    textQuery: "mechanical contractor",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },
  {
    id: "fire-sprinkler",
    label: "Fire Sprinkler",
    nearbyPrimaryType: null,
    textQuery: "fire sprinkler contractor",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },
  {
    id: "low-voltage",
    label: "Low Voltage",
    nearbyPrimaryType: null,
    textQuery: "low voltage contractor",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },
  {
    id: "commercial-glazing",
    label: "Commercial Glazing",
    nearbyPrimaryType: null,
    textQuery: "commercial glazing contractor",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },
  {
    id: "waterproofing",
    label: "Waterproofing",
    nearbyPrimaryType: null,
    textQuery: "waterproofing contractor",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },
  {
    id: "elevator",
    label: "Elevator",
    nearbyPrimaryType: null,
    textQuery: "elevator contractor",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },
  {
    id: "millwork",
    label: "Millwork",
    nearbyPrimaryType: null,
    textQuery: "millwork contractor",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },
  {
    id: "carpentry",
    label: "Carpentry",
    nearbyPrimaryType: null,
    textQuery: "carpentry contractor",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },
  {
    id: "stucco",
    label: "Stucco",
    nearbyPrimaryType: null,
    textQuery: "stucco contractor",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },
  {
    id: "scaffolding",
    label: "Scaffolding",
    nearbyPrimaryType: null,
    textQuery: "scaffolding contractor",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },

  // === Marine / coastal ===
  {
    id: "marine",
    label: "Marine",
    nearbyPrimaryType: null,
    textQuery: "marine contractor",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },
  {
    id: "pile-driving",
    label: "Pile Driving",
    nearbyPrimaryType: null,
    textQuery: "pile driving contractor",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },

  // === Restoration & environmental ===
  {
    id: "property-restoration",
    label: "Property Restoration",
    nearbyPrimaryType: null,
    textQuery: "property restoration",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },
  {
    id: "environmental",
    label: "Environmental",
    nearbyPrimaryType: null,
    textQuery: "environmental contractor",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },

  // === Industrial / fabrication ===
  {
    id: "structural-steel-fabricator",
    label: "Structural Steel Fabricator",
    nearbyPrimaryType: null,
    textQuery: "structural steel fabricator",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },
  {
    id: "metal-building-manufacturer",
    label: "Metal Building Manufacturer",
    nearbyPrimaryType: null,
    textQuery: "metal building manufacturer",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },
  {
    id: "modular-building-manufacturer",
    label: "Modular Building Manufacturer",
    nearbyPrimaryType: null,
    textQuery: "modular building manufacturer",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },
  {
    id: "welding",
    label: "Welding",
    nearbyPrimaryType: null,
    textQuery: "welding shop",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },
  {
    id: "machine-shop",
    label: "Machine Shop",
    nearbyPrimaryType: null,
    textQuery: "machine shop",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },

  // === Drilling ===
  {
    id: "offshore-drilling",
    label: "Offshore Drilling",
    nearbyPrimaryType: null,
    textQuery: "offshore drilling company",
    textIncludedType: null,
    minNearbyResultsBeforeFallback: 2,
  },
];
